// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greptime.proto

package org.greptimedb.v1;

public final class GreptimeDB {
  private GreptimeDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BatchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greptime.v1.BatchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    java.util.List<org.greptimedb.v1.Admin.AdminRequest> 
        getAdminsList();
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    org.greptimedb.v1.Admin.AdminRequest getAdmins(int index);
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    int getAdminsCount();
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    java.util.List<? extends org.greptimedb.v1.Admin.AdminRequestOrBuilder> 
        getAdminsOrBuilderList();
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    org.greptimedb.v1.Admin.AdminRequestOrBuilder getAdminsOrBuilder(
        int index);

    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    java.util.List<org.greptimedb.v1.Database.DatabaseRequest> 
        getDatabasesList();
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    org.greptimedb.v1.Database.DatabaseRequest getDatabases(int index);
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    int getDatabasesCount();
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    java.util.List<? extends org.greptimedb.v1.Database.DatabaseRequestOrBuilder> 
        getDatabasesOrBuilderList();
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    org.greptimedb.v1.Database.DatabaseRequestOrBuilder getDatabasesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code greptime.v1.BatchRequest}
   */
  public static final class BatchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greptime.v1.BatchRequest)
      BatchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BatchRequest.newBuilder() to construct.
    private BatchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BatchRequest() {
      admins_ = java.util.Collections.emptyList();
      databases_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BatchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BatchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                admins_ = new java.util.ArrayList<org.greptimedb.v1.Admin.AdminRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              admins_.add(
                  input.readMessage(org.greptimedb.v1.Admin.AdminRequest.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                databases_ = new java.util.ArrayList<org.greptimedb.v1.Database.DatabaseRequest>();
                mutable_bitField0_ |= 0x00000002;
              }
              databases_.add(
                  input.readMessage(org.greptimedb.v1.Database.DatabaseRequest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          admins_ = java.util.Collections.unmodifiableList(admins_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          databases_ = java.util.Collections.unmodifiableList(databases_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.greptimedb.v1.GreptimeDB.BatchRequest.class, org.greptimedb.v1.GreptimeDB.BatchRequest.Builder.class);
    }

    public static final int ADMINS_FIELD_NUMBER = 1;
    private java.util.List<org.greptimedb.v1.Admin.AdminRequest> admins_;
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.greptimedb.v1.Admin.AdminRequest> getAdminsList() {
      return admins_;
    }
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.greptimedb.v1.Admin.AdminRequestOrBuilder> 
        getAdminsOrBuilderList() {
      return admins_;
    }
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    @java.lang.Override
    public int getAdminsCount() {
      return admins_.size();
    }
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Admin.AdminRequest getAdmins(int index) {
      return admins_.get(index);
    }
    /**
     * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Admin.AdminRequestOrBuilder getAdminsOrBuilder(
        int index) {
      return admins_.get(index);
    }

    public static final int DATABASES_FIELD_NUMBER = 2;
    private java.util.List<org.greptimedb.v1.Database.DatabaseRequest> databases_;
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.greptimedb.v1.Database.DatabaseRequest> getDatabasesList() {
      return databases_;
    }
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.greptimedb.v1.Database.DatabaseRequestOrBuilder> 
        getDatabasesOrBuilderList() {
      return databases_;
    }
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    @java.lang.Override
    public int getDatabasesCount() {
      return databases_.size();
    }
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Database.DatabaseRequest getDatabases(int index) {
      return databases_.get(index);
    }
    /**
     * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Database.DatabaseRequestOrBuilder getDatabasesOrBuilder(
        int index) {
      return databases_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < admins_.size(); i++) {
        output.writeMessage(1, admins_.get(i));
      }
      for (int i = 0; i < databases_.size(); i++) {
        output.writeMessage(2, databases_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < admins_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, admins_.get(i));
      }
      for (int i = 0; i < databases_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, databases_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.greptimedb.v1.GreptimeDB.BatchRequest)) {
        return super.equals(obj);
      }
      org.greptimedb.v1.GreptimeDB.BatchRequest other = (org.greptimedb.v1.GreptimeDB.BatchRequest) obj;

      if (!getAdminsList()
          .equals(other.getAdminsList())) return false;
      if (!getDatabasesList()
          .equals(other.getDatabasesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAdminsCount() > 0) {
        hash = (37 * hash) + ADMINS_FIELD_NUMBER;
        hash = (53 * hash) + getAdminsList().hashCode();
      }
      if (getDatabasesCount() > 0) {
        hash = (37 * hash) + DATABASES_FIELD_NUMBER;
        hash = (53 * hash) + getDatabasesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.greptimedb.v1.GreptimeDB.BatchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greptime.v1.BatchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greptime.v1.BatchRequest)
        org.greptimedb.v1.GreptimeDB.BatchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.greptimedb.v1.GreptimeDB.BatchRequest.class, org.greptimedb.v1.GreptimeDB.BatchRequest.Builder.class);
      }

      // Construct using org.greptimedb.v1.GreptimeDB.BatchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAdminsFieldBuilder();
          getDatabasesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (adminsBuilder_ == null) {
          admins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          adminsBuilder_.clear();
        }
        if (databasesBuilder_ == null) {
          databases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          databasesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchRequest_descriptor;
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchRequest getDefaultInstanceForType() {
        return org.greptimedb.v1.GreptimeDB.BatchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchRequest build() {
        org.greptimedb.v1.GreptimeDB.BatchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchRequest buildPartial() {
        org.greptimedb.v1.GreptimeDB.BatchRequest result = new org.greptimedb.v1.GreptimeDB.BatchRequest(this);
        int from_bitField0_ = bitField0_;
        if (adminsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            admins_ = java.util.Collections.unmodifiableList(admins_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.admins_ = admins_;
        } else {
          result.admins_ = adminsBuilder_.build();
        }
        if (databasesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            databases_ = java.util.Collections.unmodifiableList(databases_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.databases_ = databases_;
        } else {
          result.databases_ = databasesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.greptimedb.v1.GreptimeDB.BatchRequest) {
          return mergeFrom((org.greptimedb.v1.GreptimeDB.BatchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.greptimedb.v1.GreptimeDB.BatchRequest other) {
        if (other == org.greptimedb.v1.GreptimeDB.BatchRequest.getDefaultInstance()) return this;
        if (adminsBuilder_ == null) {
          if (!other.admins_.isEmpty()) {
            if (admins_.isEmpty()) {
              admins_ = other.admins_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAdminsIsMutable();
              admins_.addAll(other.admins_);
            }
            onChanged();
          }
        } else {
          if (!other.admins_.isEmpty()) {
            if (adminsBuilder_.isEmpty()) {
              adminsBuilder_.dispose();
              adminsBuilder_ = null;
              admins_ = other.admins_;
              bitField0_ = (bitField0_ & ~0x00000001);
              adminsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAdminsFieldBuilder() : null;
            } else {
              adminsBuilder_.addAllMessages(other.admins_);
            }
          }
        }
        if (databasesBuilder_ == null) {
          if (!other.databases_.isEmpty()) {
            if (databases_.isEmpty()) {
              databases_ = other.databases_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDatabasesIsMutable();
              databases_.addAll(other.databases_);
            }
            onChanged();
          }
        } else {
          if (!other.databases_.isEmpty()) {
            if (databasesBuilder_.isEmpty()) {
              databasesBuilder_.dispose();
              databasesBuilder_ = null;
              databases_ = other.databases_;
              bitField0_ = (bitField0_ & ~0x00000002);
              databasesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDatabasesFieldBuilder() : null;
            } else {
              databasesBuilder_.addAllMessages(other.databases_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.greptimedb.v1.GreptimeDB.BatchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.greptimedb.v1.GreptimeDB.BatchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.greptimedb.v1.Admin.AdminRequest> admins_ =
        java.util.Collections.emptyList();
      private void ensureAdminsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          admins_ = new java.util.ArrayList<org.greptimedb.v1.Admin.AdminRequest>(admins_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Admin.AdminRequest, org.greptimedb.v1.Admin.AdminRequest.Builder, org.greptimedb.v1.Admin.AdminRequestOrBuilder> adminsBuilder_;

      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public java.util.List<org.greptimedb.v1.Admin.AdminRequest> getAdminsList() {
        if (adminsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(admins_);
        } else {
          return adminsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public int getAdminsCount() {
        if (adminsBuilder_ == null) {
          return admins_.size();
        } else {
          return adminsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminRequest getAdmins(int index) {
        if (adminsBuilder_ == null) {
          return admins_.get(index);
        } else {
          return adminsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder setAdmins(
          int index, org.greptimedb.v1.Admin.AdminRequest value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.set(index, value);
          onChanged();
        } else {
          adminsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder setAdmins(
          int index, org.greptimedb.v1.Admin.AdminRequest.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.set(index, builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder addAdmins(org.greptimedb.v1.Admin.AdminRequest value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.add(value);
          onChanged();
        } else {
          adminsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder addAdmins(
          int index, org.greptimedb.v1.Admin.AdminRequest value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.add(index, value);
          onChanged();
        } else {
          adminsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder addAdmins(
          org.greptimedb.v1.Admin.AdminRequest.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.add(builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder addAdmins(
          int index, org.greptimedb.v1.Admin.AdminRequest.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.add(index, builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder addAllAdmins(
          java.lang.Iterable<? extends org.greptimedb.v1.Admin.AdminRequest> values) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, admins_);
          onChanged();
        } else {
          adminsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder clearAdmins() {
        if (adminsBuilder_ == null) {
          admins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          adminsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public Builder removeAdmins(int index) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.remove(index);
          onChanged();
        } else {
          adminsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminRequest.Builder getAdminsBuilder(
          int index) {
        return getAdminsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminRequestOrBuilder getAdminsOrBuilder(
          int index) {
        if (adminsBuilder_ == null) {
          return admins_.get(index);  } else {
          return adminsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public java.util.List<? extends org.greptimedb.v1.Admin.AdminRequestOrBuilder> 
           getAdminsOrBuilderList() {
        if (adminsBuilder_ != null) {
          return adminsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(admins_);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminRequest.Builder addAdminsBuilder() {
        return getAdminsFieldBuilder().addBuilder(
            org.greptimedb.v1.Admin.AdminRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminRequest.Builder addAdminsBuilder(
          int index) {
        return getAdminsFieldBuilder().addBuilder(
            index, org.greptimedb.v1.Admin.AdminRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.AdminRequest admins = 1;</code>
       */
      public java.util.List<org.greptimedb.v1.Admin.AdminRequest.Builder> 
           getAdminsBuilderList() {
        return getAdminsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Admin.AdminRequest, org.greptimedb.v1.Admin.AdminRequest.Builder, org.greptimedb.v1.Admin.AdminRequestOrBuilder> 
          getAdminsFieldBuilder() {
        if (adminsBuilder_ == null) {
          adminsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.greptimedb.v1.Admin.AdminRequest, org.greptimedb.v1.Admin.AdminRequest.Builder, org.greptimedb.v1.Admin.AdminRequestOrBuilder>(
                  admins_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          admins_ = null;
        }
        return adminsBuilder_;
      }

      private java.util.List<org.greptimedb.v1.Database.DatabaseRequest> databases_ =
        java.util.Collections.emptyList();
      private void ensureDatabasesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          databases_ = new java.util.ArrayList<org.greptimedb.v1.Database.DatabaseRequest>(databases_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Database.DatabaseRequest, org.greptimedb.v1.Database.DatabaseRequest.Builder, org.greptimedb.v1.Database.DatabaseRequestOrBuilder> databasesBuilder_;

      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public java.util.List<org.greptimedb.v1.Database.DatabaseRequest> getDatabasesList() {
        if (databasesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(databases_);
        } else {
          return databasesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public int getDatabasesCount() {
        if (databasesBuilder_ == null) {
          return databases_.size();
        } else {
          return databasesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseRequest getDatabases(int index) {
        if (databasesBuilder_ == null) {
          return databases_.get(index);
        } else {
          return databasesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder setDatabases(
          int index, org.greptimedb.v1.Database.DatabaseRequest value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.set(index, value);
          onChanged();
        } else {
          databasesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder setDatabases(
          int index, org.greptimedb.v1.Database.DatabaseRequest.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.set(index, builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder addDatabases(org.greptimedb.v1.Database.DatabaseRequest value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.add(value);
          onChanged();
        } else {
          databasesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder addDatabases(
          int index, org.greptimedb.v1.Database.DatabaseRequest value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.add(index, value);
          onChanged();
        } else {
          databasesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder addDatabases(
          org.greptimedb.v1.Database.DatabaseRequest.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.add(builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder addDatabases(
          int index, org.greptimedb.v1.Database.DatabaseRequest.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.add(index, builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder addAllDatabases(
          java.lang.Iterable<? extends org.greptimedb.v1.Database.DatabaseRequest> values) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, databases_);
          onChanged();
        } else {
          databasesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder clearDatabases() {
        if (databasesBuilder_ == null) {
          databases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          databasesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public Builder removeDatabases(int index) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.remove(index);
          onChanged();
        } else {
          databasesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseRequest.Builder getDatabasesBuilder(
          int index) {
        return getDatabasesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseRequestOrBuilder getDatabasesOrBuilder(
          int index) {
        if (databasesBuilder_ == null) {
          return databases_.get(index);  } else {
          return databasesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public java.util.List<? extends org.greptimedb.v1.Database.DatabaseRequestOrBuilder> 
           getDatabasesOrBuilderList() {
        if (databasesBuilder_ != null) {
          return databasesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(databases_);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseRequest.Builder addDatabasesBuilder() {
        return getDatabasesFieldBuilder().addBuilder(
            org.greptimedb.v1.Database.DatabaseRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseRequest.Builder addDatabasesBuilder(
          int index) {
        return getDatabasesFieldBuilder().addBuilder(
            index, org.greptimedb.v1.Database.DatabaseRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.DatabaseRequest databases = 2;</code>
       */
      public java.util.List<org.greptimedb.v1.Database.DatabaseRequest.Builder> 
           getDatabasesBuilderList() {
        return getDatabasesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Database.DatabaseRequest, org.greptimedb.v1.Database.DatabaseRequest.Builder, org.greptimedb.v1.Database.DatabaseRequestOrBuilder> 
          getDatabasesFieldBuilder() {
        if (databasesBuilder_ == null) {
          databasesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.greptimedb.v1.Database.DatabaseRequest, org.greptimedb.v1.Database.DatabaseRequest.Builder, org.greptimedb.v1.Database.DatabaseRequestOrBuilder>(
                  databases_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          databases_ = null;
        }
        return databasesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greptime.v1.BatchRequest)
    }

    // @@protoc_insertion_point(class_scope:greptime.v1.BatchRequest)
    private static final org.greptimedb.v1.GreptimeDB.BatchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.greptimedb.v1.GreptimeDB.BatchRequest();
    }

    public static org.greptimedb.v1.GreptimeDB.BatchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BatchRequest>
        PARSER = new com.google.protobuf.AbstractParser<BatchRequest>() {
      @java.lang.Override
      public BatchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BatchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BatchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.greptimedb.v1.GreptimeDB.BatchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greptime.v1.BatchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    java.util.List<org.greptimedb.v1.Admin.AdminResponse> 
        getAdminsList();
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    org.greptimedb.v1.Admin.AdminResponse getAdmins(int index);
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    int getAdminsCount();
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    java.util.List<? extends org.greptimedb.v1.Admin.AdminResponseOrBuilder> 
        getAdminsOrBuilderList();
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    org.greptimedb.v1.Admin.AdminResponseOrBuilder getAdminsOrBuilder(
        int index);

    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    java.util.List<org.greptimedb.v1.Database.DatabaseResponse> 
        getDatabasesList();
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    org.greptimedb.v1.Database.DatabaseResponse getDatabases(int index);
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    int getDatabasesCount();
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    java.util.List<? extends org.greptimedb.v1.Database.DatabaseResponseOrBuilder> 
        getDatabasesOrBuilderList();
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    org.greptimedb.v1.Database.DatabaseResponseOrBuilder getDatabasesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code greptime.v1.BatchResponse}
   */
  public static final class BatchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greptime.v1.BatchResponse)
      BatchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BatchResponse.newBuilder() to construct.
    private BatchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BatchResponse() {
      admins_ = java.util.Collections.emptyList();
      databases_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BatchResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BatchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                admins_ = new java.util.ArrayList<org.greptimedb.v1.Admin.AdminResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              admins_.add(
                  input.readMessage(org.greptimedb.v1.Admin.AdminResponse.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                databases_ = new java.util.ArrayList<org.greptimedb.v1.Database.DatabaseResponse>();
                mutable_bitField0_ |= 0x00000002;
              }
              databases_.add(
                  input.readMessage(org.greptimedb.v1.Database.DatabaseResponse.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          admins_ = java.util.Collections.unmodifiableList(admins_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          databases_ = java.util.Collections.unmodifiableList(databases_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.greptimedb.v1.GreptimeDB.BatchResponse.class, org.greptimedb.v1.GreptimeDB.BatchResponse.Builder.class);
    }

    public static final int ADMINS_FIELD_NUMBER = 1;
    private java.util.List<org.greptimedb.v1.Admin.AdminResponse> admins_;
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.greptimedb.v1.Admin.AdminResponse> getAdminsList() {
      return admins_;
    }
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.greptimedb.v1.Admin.AdminResponseOrBuilder> 
        getAdminsOrBuilderList() {
      return admins_;
    }
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    @java.lang.Override
    public int getAdminsCount() {
      return admins_.size();
    }
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Admin.AdminResponse getAdmins(int index) {
      return admins_.get(index);
    }
    /**
     * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Admin.AdminResponseOrBuilder getAdminsOrBuilder(
        int index) {
      return admins_.get(index);
    }

    public static final int DATABASES_FIELD_NUMBER = 2;
    private java.util.List<org.greptimedb.v1.Database.DatabaseResponse> databases_;
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.greptimedb.v1.Database.DatabaseResponse> getDatabasesList() {
      return databases_;
    }
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.greptimedb.v1.Database.DatabaseResponseOrBuilder> 
        getDatabasesOrBuilderList() {
      return databases_;
    }
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    @java.lang.Override
    public int getDatabasesCount() {
      return databases_.size();
    }
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Database.DatabaseResponse getDatabases(int index) {
      return databases_.get(index);
    }
    /**
     * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
     */
    @java.lang.Override
    public org.greptimedb.v1.Database.DatabaseResponseOrBuilder getDatabasesOrBuilder(
        int index) {
      return databases_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < admins_.size(); i++) {
        output.writeMessage(1, admins_.get(i));
      }
      for (int i = 0; i < databases_.size(); i++) {
        output.writeMessage(2, databases_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < admins_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, admins_.get(i));
      }
      for (int i = 0; i < databases_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, databases_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.greptimedb.v1.GreptimeDB.BatchResponse)) {
        return super.equals(obj);
      }
      org.greptimedb.v1.GreptimeDB.BatchResponse other = (org.greptimedb.v1.GreptimeDB.BatchResponse) obj;

      if (!getAdminsList()
          .equals(other.getAdminsList())) return false;
      if (!getDatabasesList()
          .equals(other.getDatabasesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAdminsCount() > 0) {
        hash = (37 * hash) + ADMINS_FIELD_NUMBER;
        hash = (53 * hash) + getAdminsList().hashCode();
      }
      if (getDatabasesCount() > 0) {
        hash = (37 * hash) + DATABASES_FIELD_NUMBER;
        hash = (53 * hash) + getDatabasesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.greptimedb.v1.GreptimeDB.BatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.greptimedb.v1.GreptimeDB.BatchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greptime.v1.BatchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greptime.v1.BatchResponse)
        org.greptimedb.v1.GreptimeDB.BatchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.greptimedb.v1.GreptimeDB.BatchResponse.class, org.greptimedb.v1.GreptimeDB.BatchResponse.Builder.class);
      }

      // Construct using org.greptimedb.v1.GreptimeDB.BatchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAdminsFieldBuilder();
          getDatabasesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (adminsBuilder_ == null) {
          admins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          adminsBuilder_.clear();
        }
        if (databasesBuilder_ == null) {
          databases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          databasesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.greptimedb.v1.GreptimeDB.internal_static_greptime_v1_BatchResponse_descriptor;
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchResponse getDefaultInstanceForType() {
        return org.greptimedb.v1.GreptimeDB.BatchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchResponse build() {
        org.greptimedb.v1.GreptimeDB.BatchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.greptimedb.v1.GreptimeDB.BatchResponse buildPartial() {
        org.greptimedb.v1.GreptimeDB.BatchResponse result = new org.greptimedb.v1.GreptimeDB.BatchResponse(this);
        int from_bitField0_ = bitField0_;
        if (adminsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            admins_ = java.util.Collections.unmodifiableList(admins_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.admins_ = admins_;
        } else {
          result.admins_ = adminsBuilder_.build();
        }
        if (databasesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            databases_ = java.util.Collections.unmodifiableList(databases_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.databases_ = databases_;
        } else {
          result.databases_ = databasesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.greptimedb.v1.GreptimeDB.BatchResponse) {
          return mergeFrom((org.greptimedb.v1.GreptimeDB.BatchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.greptimedb.v1.GreptimeDB.BatchResponse other) {
        if (other == org.greptimedb.v1.GreptimeDB.BatchResponse.getDefaultInstance()) return this;
        if (adminsBuilder_ == null) {
          if (!other.admins_.isEmpty()) {
            if (admins_.isEmpty()) {
              admins_ = other.admins_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAdminsIsMutable();
              admins_.addAll(other.admins_);
            }
            onChanged();
          }
        } else {
          if (!other.admins_.isEmpty()) {
            if (adminsBuilder_.isEmpty()) {
              adminsBuilder_.dispose();
              adminsBuilder_ = null;
              admins_ = other.admins_;
              bitField0_ = (bitField0_ & ~0x00000001);
              adminsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAdminsFieldBuilder() : null;
            } else {
              adminsBuilder_.addAllMessages(other.admins_);
            }
          }
        }
        if (databasesBuilder_ == null) {
          if (!other.databases_.isEmpty()) {
            if (databases_.isEmpty()) {
              databases_ = other.databases_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDatabasesIsMutable();
              databases_.addAll(other.databases_);
            }
            onChanged();
          }
        } else {
          if (!other.databases_.isEmpty()) {
            if (databasesBuilder_.isEmpty()) {
              databasesBuilder_.dispose();
              databasesBuilder_ = null;
              databases_ = other.databases_;
              bitField0_ = (bitField0_ & ~0x00000002);
              databasesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDatabasesFieldBuilder() : null;
            } else {
              databasesBuilder_.addAllMessages(other.databases_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.greptimedb.v1.GreptimeDB.BatchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.greptimedb.v1.GreptimeDB.BatchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.greptimedb.v1.Admin.AdminResponse> admins_ =
        java.util.Collections.emptyList();
      private void ensureAdminsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          admins_ = new java.util.ArrayList<org.greptimedb.v1.Admin.AdminResponse>(admins_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Admin.AdminResponse, org.greptimedb.v1.Admin.AdminResponse.Builder, org.greptimedb.v1.Admin.AdminResponseOrBuilder> adminsBuilder_;

      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public java.util.List<org.greptimedb.v1.Admin.AdminResponse> getAdminsList() {
        if (adminsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(admins_);
        } else {
          return adminsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public int getAdminsCount() {
        if (adminsBuilder_ == null) {
          return admins_.size();
        } else {
          return adminsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminResponse getAdmins(int index) {
        if (adminsBuilder_ == null) {
          return admins_.get(index);
        } else {
          return adminsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder setAdmins(
          int index, org.greptimedb.v1.Admin.AdminResponse value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.set(index, value);
          onChanged();
        } else {
          adminsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder setAdmins(
          int index, org.greptimedb.v1.Admin.AdminResponse.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.set(index, builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder addAdmins(org.greptimedb.v1.Admin.AdminResponse value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.add(value);
          onChanged();
        } else {
          adminsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder addAdmins(
          int index, org.greptimedb.v1.Admin.AdminResponse value) {
        if (adminsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdminsIsMutable();
          admins_.add(index, value);
          onChanged();
        } else {
          adminsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder addAdmins(
          org.greptimedb.v1.Admin.AdminResponse.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.add(builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder addAdmins(
          int index, org.greptimedb.v1.Admin.AdminResponse.Builder builderForValue) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.add(index, builderForValue.build());
          onChanged();
        } else {
          adminsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder addAllAdmins(
          java.lang.Iterable<? extends org.greptimedb.v1.Admin.AdminResponse> values) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, admins_);
          onChanged();
        } else {
          adminsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder clearAdmins() {
        if (adminsBuilder_ == null) {
          admins_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          adminsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public Builder removeAdmins(int index) {
        if (adminsBuilder_ == null) {
          ensureAdminsIsMutable();
          admins_.remove(index);
          onChanged();
        } else {
          adminsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminResponse.Builder getAdminsBuilder(
          int index) {
        return getAdminsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminResponseOrBuilder getAdminsOrBuilder(
          int index) {
        if (adminsBuilder_ == null) {
          return admins_.get(index);  } else {
          return adminsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public java.util.List<? extends org.greptimedb.v1.Admin.AdminResponseOrBuilder> 
           getAdminsOrBuilderList() {
        if (adminsBuilder_ != null) {
          return adminsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(admins_);
        }
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminResponse.Builder addAdminsBuilder() {
        return getAdminsFieldBuilder().addBuilder(
            org.greptimedb.v1.Admin.AdminResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public org.greptimedb.v1.Admin.AdminResponse.Builder addAdminsBuilder(
          int index) {
        return getAdminsFieldBuilder().addBuilder(
            index, org.greptimedb.v1.Admin.AdminResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.AdminResponse admins = 1;</code>
       */
      public java.util.List<org.greptimedb.v1.Admin.AdminResponse.Builder> 
           getAdminsBuilderList() {
        return getAdminsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Admin.AdminResponse, org.greptimedb.v1.Admin.AdminResponse.Builder, org.greptimedb.v1.Admin.AdminResponseOrBuilder> 
          getAdminsFieldBuilder() {
        if (adminsBuilder_ == null) {
          adminsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.greptimedb.v1.Admin.AdminResponse, org.greptimedb.v1.Admin.AdminResponse.Builder, org.greptimedb.v1.Admin.AdminResponseOrBuilder>(
                  admins_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          admins_ = null;
        }
        return adminsBuilder_;
      }

      private java.util.List<org.greptimedb.v1.Database.DatabaseResponse> databases_ =
        java.util.Collections.emptyList();
      private void ensureDatabasesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          databases_ = new java.util.ArrayList<org.greptimedb.v1.Database.DatabaseResponse>(databases_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Database.DatabaseResponse, org.greptimedb.v1.Database.DatabaseResponse.Builder, org.greptimedb.v1.Database.DatabaseResponseOrBuilder> databasesBuilder_;

      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public java.util.List<org.greptimedb.v1.Database.DatabaseResponse> getDatabasesList() {
        if (databasesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(databases_);
        } else {
          return databasesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public int getDatabasesCount() {
        if (databasesBuilder_ == null) {
          return databases_.size();
        } else {
          return databasesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseResponse getDatabases(int index) {
        if (databasesBuilder_ == null) {
          return databases_.get(index);
        } else {
          return databasesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder setDatabases(
          int index, org.greptimedb.v1.Database.DatabaseResponse value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.set(index, value);
          onChanged();
        } else {
          databasesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder setDatabases(
          int index, org.greptimedb.v1.Database.DatabaseResponse.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.set(index, builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder addDatabases(org.greptimedb.v1.Database.DatabaseResponse value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.add(value);
          onChanged();
        } else {
          databasesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder addDatabases(
          int index, org.greptimedb.v1.Database.DatabaseResponse value) {
        if (databasesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatabasesIsMutable();
          databases_.add(index, value);
          onChanged();
        } else {
          databasesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder addDatabases(
          org.greptimedb.v1.Database.DatabaseResponse.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.add(builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder addDatabases(
          int index, org.greptimedb.v1.Database.DatabaseResponse.Builder builderForValue) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.add(index, builderForValue.build());
          onChanged();
        } else {
          databasesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder addAllDatabases(
          java.lang.Iterable<? extends org.greptimedb.v1.Database.DatabaseResponse> values) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, databases_);
          onChanged();
        } else {
          databasesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder clearDatabases() {
        if (databasesBuilder_ == null) {
          databases_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          databasesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public Builder removeDatabases(int index) {
        if (databasesBuilder_ == null) {
          ensureDatabasesIsMutable();
          databases_.remove(index);
          onChanged();
        } else {
          databasesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseResponse.Builder getDatabasesBuilder(
          int index) {
        return getDatabasesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseResponseOrBuilder getDatabasesOrBuilder(
          int index) {
        if (databasesBuilder_ == null) {
          return databases_.get(index);  } else {
          return databasesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public java.util.List<? extends org.greptimedb.v1.Database.DatabaseResponseOrBuilder> 
           getDatabasesOrBuilderList() {
        if (databasesBuilder_ != null) {
          return databasesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(databases_);
        }
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseResponse.Builder addDatabasesBuilder() {
        return getDatabasesFieldBuilder().addBuilder(
            org.greptimedb.v1.Database.DatabaseResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public org.greptimedb.v1.Database.DatabaseResponse.Builder addDatabasesBuilder(
          int index) {
        return getDatabasesFieldBuilder().addBuilder(
            index, org.greptimedb.v1.Database.DatabaseResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .greptime.v1.DatabaseResponse databases = 2;</code>
       */
      public java.util.List<org.greptimedb.v1.Database.DatabaseResponse.Builder> 
           getDatabasesBuilderList() {
        return getDatabasesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.greptimedb.v1.Database.DatabaseResponse, org.greptimedb.v1.Database.DatabaseResponse.Builder, org.greptimedb.v1.Database.DatabaseResponseOrBuilder> 
          getDatabasesFieldBuilder() {
        if (databasesBuilder_ == null) {
          databasesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.greptimedb.v1.Database.DatabaseResponse, org.greptimedb.v1.Database.DatabaseResponse.Builder, org.greptimedb.v1.Database.DatabaseResponseOrBuilder>(
                  databases_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          databases_ = null;
        }
        return databasesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greptime.v1.BatchResponse)
    }

    // @@protoc_insertion_point(class_scope:greptime.v1.BatchResponse)
    private static final org.greptimedb.v1.GreptimeDB.BatchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.greptimedb.v1.GreptimeDB.BatchResponse();
    }

    public static org.greptimedb.v1.GreptimeDB.BatchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BatchResponse>
        PARSER = new com.google.protobuf.AbstractParser<BatchResponse>() {
      @java.lang.Override
      public BatchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BatchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BatchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.greptimedb.v1.GreptimeDB.BatchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greptime_v1_BatchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greptime_v1_BatchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greptime_v1_BatchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greptime_v1_BatchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016greptime.proto\022\013greptime.v1\032\013admin.pro" +
      "to\032\016database.proto\"j\n\014BatchRequest\022)\n\006ad" +
      "mins\030\001 \003(\0132\031.greptime.v1.AdminRequest\022/\n" +
      "\tdatabases\030\002 \003(\0132\034.greptime.v1.DatabaseR" +
      "equest\"m\n\rBatchResponse\022*\n\006admins\030\001 \003(\0132" +
      "\032.greptime.v1.AdminResponse\0220\n\tdatabases" +
      "\030\002 \003(\0132\035.greptime.v1.DatabaseResponse2L\n" +
      "\010Greptime\022@\n\005Batch\022\031.greptime.v1.BatchRe" +
      "quest\032\032.greptime.v1.BatchResponse\"\000B\037\n\021o" +
      "rg.greptimedb.v1B\nGreptimeDBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.greptimedb.v1.Admin.getDescriptor(),
          org.greptimedb.v1.Database.getDescriptor(),
        });
    internal_static_greptime_v1_BatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greptime_v1_BatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greptime_v1_BatchRequest_descriptor,
        new java.lang.String[] { "Admins", "Databases", });
    internal_static_greptime_v1_BatchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_greptime_v1_BatchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greptime_v1_BatchResponse_descriptor,
        new java.lang.String[] { "Admins", "Databases", });
    org.greptimedb.v1.Admin.getDescriptor();
    org.greptimedb.v1.Database.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
